// ============================================================================
// Capacity Platform — TypeScript types
// ----------------------------------------------------------------------------
// Locally-defined row/insert/update types for the 5 capacity-platform tables
// and 4 RPCs. These mirror the live SQL definitions verbatim:
//   - migrations/20260429000007_capacity_platform_capacity_settings.sql
//   - migrations/20260429000008_capacity_platform_capacity_allocations.sql
//   - migrations/20260429000009_capacity_platform_work_requests.sql
//   - migrations/20260429000010_capacity_platform_quarterly_forecast.sql
//   - migrations/20260429000011_capacity_platform_get_capacity_live.sql
//   - migrations/20260429000012_capacity_platform_get_skill_matrix.sql
//   - migrations/20260429000013_capacity_platform_get_fte_loss_summary.sql
//   - migrations/20260429000016_capacity_platform_seed_skills.sql
//
// These are intentionally a parallel definition until `src/integrations/
// supabase/types.ts` is regenerated. Once the autogenerated `Database` type
// is fresh, the wrappers in this folder can be migrated to use
// `Database['public']['Tables'][...]['Row']` and these locals deleted.
// ============================================================================

// --- Enums ------------------------------------------------------------------

export type WorkType =
  | "BAU"
  | "Project"
  | "Onboarding"
  | "Escalation"
  | "Internal";

export type WorkRequestStatus =
  | "New"
  | "Allocated"
  | "In Progress"
  | "On Hold"
  | "Complete"
  | "Cancelled";

export type RagStatus = "Red" | "Amber" | "Green";

// Reused from the platform's existing task_priority enum.
export type TaskPriority = "low" | "medium" | "high" | "urgent";

// --- Table rows -------------------------------------------------------------

export interface SkillRow {
  id: string;
  code: string;
  name: string;
  category_id: string | null;
  weight: number;
  display_order: number | null;
  is_active: boolean;
  created_at?: string;
  updated_at?: string;
}

export type SkillInsert = Omit<SkillRow, "id" | "created_at" | "updated_at"> & {
  id?: string;
  weight?: number;
  display_order?: number | null;
  is_active?: boolean;
};

export type SkillUpdate = Partial<SkillInsert>;

export interface CapacitySettingRow {
  key: string;
  // jsonb — boolean | number | string | array | object. Cast on read.
  value: unknown;
  description: string | null;
  updated_at: string;
  updated_by: string | null;
}

export type CapacitySettingInsert = Pick<CapacitySettingRow, "key" | "value"> & {
  description?: string | null;
  updated_by?: string | null;
};

export type CapacitySettingUpdate = Partial<
  Omit<CapacitySettingInsert, "key">
>;

export interface CapacityAllocationRow {
  id: string;
  person_id: string;
  week_start_date: string; // yyyy-mm-dd, must be Monday
  customer: string;
  work_type: WorkType;
  mon_hours: number;
  tue_hours: number;
  wed_hours: number;
  thu_hours: number;
  fri_hours: number;
  sat_hours: number;
  sun_hours: number;
  total_hours: number; // generated stored
  notes: string | null;
  created_at: string;
  updated_at: string;
  created_by: string | null;
  updated_by: string | null;
}

export type CapacityAllocationInsert = Omit<
  CapacityAllocationRow,
  | "id"
  | "total_hours"
  | "created_at"
  | "updated_at"
> & {
  id?: string;
  mon_hours?: number;
  tue_hours?: number;
  wed_hours?: number;
  thu_hours?: number;
  fri_hours?: number;
  sat_hours?: number;
  sun_hours?: number;
  notes?: string | null;
  created_by?: string | null;
  updated_by?: string | null;
};

export type CapacityAllocationUpdate = Partial<
  Omit<CapacityAllocationInsert, "person_id" | "week_start_date">
> & {
  person_id?: string;
  week_start_date?: string;
};

export interface WorkRequestRow {
  id: string;
  code: string; // REQ-#### (auto-generated by trigger when null on insert)
  date_received: string; // yyyy-mm-dd
  customer: string;
  request_type: string | null;
  skill_required_id: string | null;
  estimated_hours: number | null;
  priority: TaskPriority;
  due_date: string | null;
  assigned_to_id: string | null;
  status: WorkRequestStatus;
  notes: string | null;
  created_at: string;
  updated_at: string;
  created_by: string | null;
  updated_by: string | null;
}

export type WorkRequestInsert = Omit<
  WorkRequestRow,
  "id" | "code" | "created_at" | "updated_at"
> & {
  id?: string;
  code?: string; // Optional — trigger fills if null/blank
  date_received?: string; // Defaults to current_date in SQL
  request_type?: string | null;
  skill_required_id?: string | null;
  estimated_hours?: number | null;
  priority?: TaskPriority;
  due_date?: string | null;
  assigned_to_id?: string | null;
  status?: WorkRequestStatus;
  notes?: string | null;
  created_by?: string | null;
  updated_by?: string | null;
};

export type WorkRequestUpdate = Partial<Omit<WorkRequestInsert, "code">> & {
  code?: never; // code is immutable post-insert (trigger only fires on insert)
};

export interface QuarterlyForecastRow {
  id: string;
  month: string; // yyyy-mm-01
  known_projects: string | null;
  expected_requests: string | null;
  risk_areas: string | null;
  resource_gap: string | null;
  mitigation_plan: string | null;
  rag: RagStatus;
  notes: string | null;
  created_at: string;
  updated_at: string;
  created_by: string | null;
  updated_by: string | null;
}

export type QuarterlyForecastInsert = Omit<
  QuarterlyForecastRow,
  "id" | "created_at" | "updated_at"
> & {
  id?: string;
  known_projects?: string | null;
  expected_requests?: string | null;
  risk_areas?: string | null;
  resource_gap?: string | null;
  mitigation_plan?: string | null;
  rag?: RagStatus;
  notes?: string | null;
  created_by?: string | null;
  updated_by?: string | null;
};

export type QuarterlyForecastUpdate = Partial<
  Omit<QuarterlyForecastInsert, "month">
> & {
  month?: string;
};

// --- RPC return rows --------------------------------------------------------
// Mirrors the RETURNS TABLE clauses of each RPC migration verbatim.
// Numerics arrive from PostgREST as `number` (auto-converted) when within
// safe integer range; treat as `number` for v1.

export interface CapacityLiveRow {
  person_id: string;
  full_name: string;
  email: string | null;
  employment_type: string | null;
  weekly_hours: number;
  base_weekly_capacity: number;
  leave_hours_this_week: number;
  adjusted_capacity: number;
  allocated_hours: number;
  allocation_pct: number | null;
  rag_status: RagStatus | null;
  over_allocated_on_leave: boolean;
}

export interface SkillMatrixRow {
  skill_id: string;
  skill_code: string;
  skill_name: string;
  category_id: string | null;
  category_name: string | null;
  weight: number;
  active_headcount: number;
  avg_score: number | null;
  trainers: number;
  experts: number;
  capable: number;
  aware: number;
  coverage_pct: number;
  spof_risk: string;
  risk_level: string;
  top_sme_id: string | null;
  top_sme_name: string | null;
  weighted_risk_score: number;
  action_needed: string | null;
}

export interface FteLossRow {
  period_label: string;
  period_start: string;
  period_end: string;
  total_leave_hours: number;
  fte_lost: number;
  headcount_on_leave: number;
}

export interface DashboardKpisRow {
  headcount: number;
  total_capacity_hours: number;
  leave_impact_hours: number;
  adjusted_capacity_hours: number;
  total_allocated_hours: number;
  avg_utilisation_pct: number;
  red_count: number;
  amber_count: number;
  green_count: number;
  spof_skills_count: number;
}

// --- RPC input shapes -------------------------------------------------------

export interface PeriodInput {
  label: string;
  start: string; // yyyy-mm-dd
  end: string;   // yyyy-mm-dd inclusive
}
