// ============================================================================
// Capacity Platform — work_requests CRUD
// ----------------------------------------------------------------------------
// Inbound work intake queue. REQ-#### codes are auto-generated by the
// before-insert trigger when `code` is null/blank. Status workflow:
//   New → Allocated → In Progress → Complete
//   (any) → On Hold → (resume) | Cancelled
// CHECK constraint: estimated_hours must be present for any status other
// than 'New' or 'Cancelled'.
// ============================================================================

import { capacitySupabase } from "./client";
import type {
  WorkRequestInsert,
  WorkRequestRow,
  WorkRequestStatus,
  WorkRequestUpdate,
} from "./types";

export interface ListWorkRequestsFilter {
  status?: WorkRequestStatus | WorkRequestStatus[];
  assignedToId?: string | null;  // pass null to find unassigned
  customer?: string;
  skillRequiredId?: string;
  /** Inclusive lower bound on date_received. */
  dateReceivedFrom?: string;
  /** Inclusive upper bound on date_received. */
  dateReceivedTo?: string;
}

export const listWorkRequests = async (
  filter: ListWorkRequestsFilter = {}
): Promise<WorkRequestRow[]> => {
  let q = capacitySupabase
    .from("work_requests")
    .select("*")
    .order("date_received", { ascending: false })
    .order("created_at", { ascending: false });

  if (filter.status) {
    if (Array.isArray(filter.status)) {
      q = q.in("status", filter.status);
    } else {
      q = q.eq("status", filter.status);
    }
  }
  if (filter.assignedToId === null) {
    q = q.is("assigned_to_id", null);
  } else if (filter.assignedToId !== undefined) {
    q = q.eq("assigned_to_id", filter.assignedToId);
  }
  if (filter.customer) {
    q = q.eq("customer", filter.customer);
  }
  if (filter.skillRequiredId) {
    q = q.eq("skill_required_id", filter.skillRequiredId);
  }
  if (filter.dateReceivedFrom) {
    q = q.gte("date_received", filter.dateReceivedFrom);
  }
  if (filter.dateReceivedTo) {
    q = q.lte("date_received", filter.dateReceivedTo);
  }

  const { data, error } = await q;
  if (error) {
    throw new Error(
      `[capacity-platform] listWorkRequests failed: ${error.message}`
    );
  }
  return (data ?? []) as WorkRequestRow[];
};

export const getWorkRequest = async (
  id: string
): Promise<WorkRequestRow | null> => {
  const { data, error } = await capacitySupabase
    .from("work_requests")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  if (error) {
    throw new Error(
      `[capacity-platform] getWorkRequest(${id}) failed: ${error.message}`
    );
  }
  return (data ?? null) as WorkRequestRow | null;
};

export const getWorkRequestByCode = async (
  code: string
): Promise<WorkRequestRow | null> => {
  const { data, error } = await capacitySupabase
    .from("work_requests")
    .select("*")
    .eq("code", code)
    .maybeSingle();

  if (error) {
    throw new Error(
      `[capacity-platform] getWorkRequestByCode(${code}) failed: ${error.message}`
    );
  }
  return (data ?? null) as WorkRequestRow | null;
};

/**
 * Insert a work request. Omit `code` to let the trigger assign REQ-####.
 * The estimated-hours-required CHECK fires when status is anything other
 * than 'New' or 'Cancelled'.
 */
export const createWorkRequest = async (
  input: WorkRequestInsert
): Promise<WorkRequestRow> => {
  const { data, error } = await capacitySupabase
    .from("work_requests")
    .insert(input)
    .select("*")
    .single();

  if (error) {
    throw new Error(
      `[capacity-platform] createWorkRequest failed: ${error.message}`
    );
  }
  return data as WorkRequestRow;
};

export const updateWorkRequest = async (
  id: string,
  patch: WorkRequestUpdate
): Promise<WorkRequestRow> => {
  const { data, error } = await capacitySupabase
    .from("work_requests")
    .update(patch)
    .eq("id", id)
    .select("*")
    .single();

  if (error) {
    throw new Error(
      `[capacity-platform] updateWorkRequest(${id}) failed: ${error.message}`
    );
  }
  return data as WorkRequestRow;
};

/**
 * Convenience: status transition with optional fields. Useful for the
 * kanban drag-handler to bake in side-effect fields (e.g. setting
 * assigned_to_id when moving to 'Allocated').
 */
export const transitionWorkRequestStatus = async (
  id: string,
  status: WorkRequestStatus,
  extra: Omit<WorkRequestUpdate, "status"> = {}
): Promise<WorkRequestRow> =>
  updateWorkRequest(id, { ...extra, status });

export const deleteWorkRequest = async (id: string): Promise<void> => {
  const { error } = await capacitySupabase
    .from("work_requests")
    .delete()
    .eq("id", id);

  if (error) {
    throw new Error(
      `[capacity-platform] deleteWorkRequest(${id}) failed: ${error.message}`
    );
  }
};
