/**
 * CSV Generation Utilities
 *
 * Common utilities for generating CSV content for exports.
 */

/**
 * Escape CSV field (handle quotes and commas)
 */
export function escapeCsvField(field: string | number | null | undefined): string {
  if (field === null || field === undefined) {
    return '';
  }

  let stringField = String(field);

  // Defuse Excel/Sheets formula injection: prefix dangerous leads with a single quote.
  // See OWASP CSV injection guidance.
  if (stringField.length > 0 && /^[=+\-@\t\r]/.test(stringField)) {
    stringField = "'" + stringField;
  }

  // If field contains comma, quote, or newline, wrap in quotes and escape internal quotes
  if (stringField.includes(',') || stringField.includes('"') || stringField.includes('\n')) {
    return `"${stringField.replace(/"/g, '""')}"`;
  }

  return stringField;
}

/**
 * Create CSV row from array of fields
 */
export function csvRowFromFields(fields: (string | number | null | undefined)[]): string {
  return fields.map(escapeCsvField).join(',');
}

/**
 * Create CSV from 2D array
 *
 * @param headers - Array of column headers
 * @param rows - 2D array of cell values
 * @param options - Optional formatting options
 */
export function csvFromRows(
  headers: string[],
  rows: (string | number | null | undefined)[][],
  options?: {
    includeHeaders?: boolean;
    lineEnding?: '\n' | '\r\n';
  }
): string {
  const { includeHeaders = true, lineEnding = '\n' } = options || {};

  const lines: string[] = [];

  if (includeHeaders) {
    lines.push(csvRowFromFields(headers));
  }

  rows.forEach((row) => {
    lines.push(csvRowFromFields(row));
  });

  return lines.join(lineEnding);
}

/**
 * Create CSV from array of objects
 *
 * @param data - Array of objects
 * @param columns - Column definitions
 */
export function csvFromObjects<T extends Record<string, unknown>>(
  data: T[],
  columns: Array<{
    key: keyof T;
    header: string;
    formatter?: (value: unknown) => string | number;
  }>,
  options?: Parameters<typeof csvFromRows>[2]
): string {
  const headers = columns.map((col) => col.header);

  const rows = data.map((item) =>
    columns.map((col) => {
      const value = item[col.key];
      const formatted = col.formatter ? col.formatter(value) : value;
      return formatted as string | number | null | undefined;
    })
  );

  return csvFromRows(headers, rows, options);
}

/**
 * Replace characters that confuse browsers / OS file systems when used
 * in download filenames (slashes, colons, etc.). Keeps periods so the
 * extension is preserved.
 */
export function sanitizeDownloadFilename(name: string): string {
  if (!name) return 'download';
  return name.replace(/[\\/:*?"<>|\r\n\t]+/g, '_').slice(0, 200);
}

/**
 * Download CSV as file
 */
export function downloadCsv(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');

  const url = URL.createObjectURL(blob);
  const safe = sanitizeDownloadFilename(filename);
  link.setAttribute('href', url);
  link.setAttribute('download', safe.endsWith('.csv') ? safe : `${safe}.csv`);
  link.style.visibility = 'hidden';

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  // Clean up
  URL.revokeObjectURL(url);
}

/**
 * Create CSV with metadata header
 */
export function csvWithMetadata(
  content: string,
  metadata: {
    title?: string;
    generatedAt?: Date;
    generatedBy?: string;
    description?: string;
  }
): string {
  const lines: string[] = [];

  if (metadata.title) {
    lines.push(`# ${metadata.title}`);
  }

  if (metadata.generatedAt) {
    lines.push(`# Generated: ${metadata.generatedAt.toLocaleString('en-AU')}`);
  }

  if (metadata.generatedBy) {
    lines.push(`# Generated by: ${metadata.generatedBy}`);
  }

  if (metadata.description) {
    lines.push(`# ${metadata.description}`);
  }

  if (lines.length > 0) {
    lines.push(''); // Empty line separator
  }

  lines.push(content);

  return lines.join('\n');
}

/**
 * Format date for CSV
 */
export function formatDateForCsv(date: Date | string): string {
  const d = typeof date === 'string' ? new Date(date) : date;
  return d.toLocaleDateString('en-AU', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  });
}

/**
 * Format datetime for CSV
 */
export function formatDateTimeForCsv(date: Date | string): string {
  const d = typeof date === 'string' ? new Date(date) : date;
  return d.toLocaleString('en-AU', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
}

/**
 * Format boolean for CSV
 */
export function formatBooleanForCsv(value: boolean | null | undefined): string {
  if (value === null || value === undefined) {
    return '';
  }
  return value ? 'Yes' : 'No';
}

/**
 * Format currency for CSV (no symbol, 2 decimals)
 */
export function formatCurrencyForCsv(amount: number | null | undefined): string {
  if (amount === null || amount === undefined) {
    return '';
  }
  return amount.toFixed(2);
}

/**
 * Parse CSV string to array of objects
 */
export function parseCsvToObjects<T extends Record<string, string>>(
  csvContent: string,
  hasHeaders: boolean = true
): T[] {
  const lines = csvContent.split('\n').filter((line) => line.trim() !== '');

  if (lines.length === 0) {
    return [];
  }

  let headers: string[] = [];
  let startIndex = 0;

  if (hasHeaders) {
    headers = parseCsvRow(lines[0]);
    startIndex = 1;
  } else {
    // Generate default headers
    const firstRow = parseCsvRow(lines[0]);
    headers = firstRow.map((_, index) => `column_${index}`);
  }

  const result: T[] = [];

  for (let i = startIndex; i < lines.length; i++) {
    const values = parseCsvRow(lines[i]);
    const obj: Record<string, string> = {};

    headers.forEach((header, index) => {
      obj[header] = values[index] || '';
    });

    result.push(obj as T);
  }

  return result;
}

/**
 * Parse a single CSV row
 */
export function parseCsvRow(row: string): string[] {
  const result: string[] = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < row.length; i++) {
    const char = row[i];
    const nextChar = row[i + 1];

    if (char === '"') {
      if (inQuotes && nextChar === '"') {
        // Escaped quote
        current += '"';
        i++; // Skip next quote
      } else {
        // Toggle quote mode
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      // Field separator
      result.push(current);
      current = '';
    } else {
      current += char;
    }
  }

  // Add last field
  result.push(current);

  return result;
}
