// ============================================================================
// WorkRequestDialog — create OR edit a work_requests row
// ----------------------------------------------------------------------------
// `mode === 'create'` → uses useCreateWorkRequest, code auto-generated by
//   the SQL trigger.
// `mode === 'edit'`   → uses useUpdateWorkRequest with the row id.
// Server-side CHECK requires estimated_hours when status not in
// ('New','Cancelled') — surfaced via validateStatusTransition.
// ============================================================================

import { useEffect, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Loader2 } from "lucide-react";
import {
  useCreateWorkRequest,
  useUpdateWorkRequest,
  useDeleteWorkRequest,
  useCapacityProfiles,
  useSkills,
} from "@/hooks/capacity-platform";
import {
  validateStatusTransition,
  WORK_REQUEST_STATUS_ORDER,
  PRIORITY_ORDER,
  PRIORITY_META,
  WORK_REQUEST_STATUS_META,
} from "@/lib/capacity-platform/workRequestStatus";
import type {
  WorkRequestRow,
  WorkRequestStatus,
  TaskPriority,
} from "@/lib/capacity-platform/types";
import AssigneeSuggestions from "./AssigneeSuggestions";

const NULL_SELECT = "__none__";

type Mode = "create" | "edit";

export interface WorkRequestDialogProps {
  open: boolean;
  onOpenChange: (next: boolean) => void;
  mode: Mode;
  request?: WorkRequestRow | null;
}

interface FormState {
  customer: string;
  request_type: string;
  skill_required_id: string;     // NULL_SELECT for none
  estimated_hours: string;
  priority: TaskPriority;
  due_date: string;
  assigned_to_id: string;        // NULL_SELECT for unassigned
  status: WorkRequestStatus;
  notes: string;
}

const emptyForm: FormState = {
  customer: "",
  request_type: "",
  skill_required_id: NULL_SELECT,
  estimated_hours: "",
  priority: "medium",
  due_date: "",
  assigned_to_id: NULL_SELECT,
  status: "New",
  notes: "",
};

const fromRow = (r: WorkRequestRow): FormState => ({
  customer: r.customer ?? "",
  request_type: r.request_type ?? "",
  skill_required_id: r.skill_required_id ?? NULL_SELECT,
  estimated_hours: r.estimated_hours == null ? "" : String(r.estimated_hours),
  priority: r.priority,
  due_date: r.due_date ?? "",
  assigned_to_id: r.assigned_to_id ?? NULL_SELECT,
  status: r.status,
  notes: r.notes ?? "",
});

const WorkRequestDialog = ({
  open,
  onOpenChange,
  mode,
  request,
}: WorkRequestDialogProps) => {
  const profilesQ = useCapacityProfiles({ activeOnly: true });
  const skillsQ = useSkills({ activeOnly: true });
  const create = useCreateWorkRequest();
  const update = useUpdateWorkRequest();
  const del = useDeleteWorkRequest();

  const [form, setForm] = useState<FormState>(emptyForm);
  const [submitError, setSubmitError] = useState<string | null>(null);

  useEffect(() => {
    if (!open) return;
    setSubmitError(null);
    if (mode === "edit" && request) setForm(fromRow(request));
    else setForm(emptyForm);
  }, [open, mode, request]);

  const trimmedCustomer = form.customer.trim();
  const estHoursTrimmed = form.estimated_hours.trim();
  let estHoursValue: number | null = null;
  let estHoursError: string | null = null;
  if (estHoursTrimmed === "") {
    estHoursValue = null;
  } else {
    const n = Number(estHoursTrimmed);
    if (!Number.isFinite(n) || n < 0) {
      estHoursError = "Must be a non-negative number.";
    } else {
      estHoursValue = Math.round(n * 100) / 100;
    }
  }

  const statusBlocker = validateStatusTransition(form.status, {
    estimated_hours: estHoursValue,
  });

  const isPending = create.isPending || update.isPending || del.isPending;
  const canSubmit =
    trimmedCustomer.length > 0 &&
    !estHoursError &&
    !statusBlocker &&
    !isPending;

  const onSubmit = async () => {
    if (!canSubmit) return;
    setSubmitError(null);
    try {
      const payload = {
        customer: trimmedCustomer,
        request_type: form.request_type.trim() || null,
        skill_required_id:
          form.skill_required_id === NULL_SELECT
            ? null
            : form.skill_required_id,
        estimated_hours: estHoursValue,
        priority: form.priority,
        due_date: form.due_date || null,
        assigned_to_id:
          form.assigned_to_id === NULL_SELECT ? null : form.assigned_to_id,
        status: form.status,
        notes: form.notes.trim() || null,
      };
      if (mode === "create") {
        await create.mutateAsync({
          ...payload,
          // date_received intentionally omitted; SQL default is current_date.
          // The shared insert type still lists it as required, so cast.
          created_by: null,
          updated_by: null,
        } as Parameters<typeof create.mutateAsync>[0]);
      } else if (request) {
        await update.mutateAsync({ id: request.id, patch: payload });
      }
      onOpenChange(false);
    } catch (err) {
      setSubmitError(err instanceof Error ? err.message : String(err));
    }
  };

  const onDelete = async () => {
    if (!request || mode !== "edit") return;
    if (!window.confirm(`Delete ${request.code}? This cannot be undone.`)) return;
    setSubmitError(null);
    try {
      await del.mutateAsync(request.id);
      onOpenChange(false);
    } catch (err) {
      setSubmitError(err instanceof Error ? err.message : String(err));
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[560px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {mode === "create"
              ? "New work request"
              : `Edit ${request?.code ?? "request"}`}
          </DialogTitle>
          <DialogDescription>
            {mode === "create"
              ? "REQ-#### code is auto-assigned on save."
              : "Update fields then Save. Status changes route through the same CHECK constraint."}
          </DialogDescription>
        </DialogHeader>

        <div className="grid gap-4 py-2">
          <div className="grid gap-1.5">
            <Label htmlFor="wr-customer">Customer*</Label>
            <Input
              id="wr-customer"
              value={form.customer}
              onChange={(e) =>
                setForm((f) => ({ ...f, customer: e.target.value }))
              }
            />
          </div>

          <div className="grid gap-1.5">
            <Label htmlFor="wr-request-type">Request type</Label>
            <Input
              id="wr-request-type"
              value={form.request_type}
              placeholder="e.g. Server outage, Onboarding, BAU support"
              onChange={(e) =>
                setForm((f) => ({ ...f, request_type: e.target.value }))
              }
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="grid gap-1.5">
              <Label htmlFor="wr-priority">Priority</Label>
              <Select
                value={form.priority}
                onValueChange={(v) =>
                  setForm((f) => ({ ...f, priority: v as TaskPriority }))
                }
              >
                <SelectTrigger id="wr-priority">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {PRIORITY_ORDER.map((p) => (
                    <SelectItem key={p} value={p}>
                      {PRIORITY_META[p].label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="grid gap-1.5">
              <Label htmlFor="wr-status">Status</Label>
              <Select
                value={form.status}
                onValueChange={(v) =>
                  setForm((f) => ({ ...f, status: v as WorkRequestStatus }))
                }
              >
                <SelectTrigger id="wr-status">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {WORK_REQUEST_STATUS_ORDER.map((s) => (
                    <SelectItem key={s} value={s}>
                      {WORK_REQUEST_STATUS_META[s].label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="grid gap-1.5">
              <Label htmlFor="wr-estimated">Estimated hours</Label>
              <Input
                id="wr-estimated"
                inputMode="decimal"
                value={form.estimated_hours}
                placeholder="e.g. 8"
                onChange={(e) =>
                  setForm((f) => ({ ...f, estimated_hours: e.target.value }))
                }
              />
              {estHoursError && (
                <span className="text-xs text-destructive">{estHoursError}</span>
              )}
            </div>

            <div className="grid gap-1.5">
              <Label htmlFor="wr-due">Due date</Label>
              <Input
                id="wr-due"
                type="date"
                value={form.due_date}
                onChange={(e) =>
                  setForm((f) => ({ ...f, due_date: e.target.value }))
                }
              />
            </div>
          </div>

          <div className="grid gap-1.5">
            <Label htmlFor="wr-skill">Skill required</Label>
            <Select
              value={form.skill_required_id}
              onValueChange={(v) =>
                setForm((f) => ({ ...f, skill_required_id: v }))
              }
            >
              <SelectTrigger id="wr-skill">
                <SelectValue placeholder="Optional…" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={NULL_SELECT}>(none)</SelectItem>
                {(skillsQ.data ?? []).map((s) => (
                  <SelectItem key={s.id} value={s.id}>
                    {s.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="grid gap-1.5">
            <Label htmlFor="wr-assigned">Assigned to</Label>
            <Select
              value={form.assigned_to_id}
              onValueChange={(v) =>
                setForm((f) => ({ ...f, assigned_to_id: v }))
              }
            >
              <SelectTrigger id="wr-assigned">
                <SelectValue placeholder="Unassigned" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={NULL_SELECT}>(unassigned)</SelectItem>
                {(profilesQ.data ?? []).map((p) => (
                  <SelectItem key={p.id} value={p.id}>
                    {p.full_name ?? p.email ?? p.id.slice(0, 8)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <AssigneeSuggestions
              skillId={
                form.skill_required_id === NULL_SELECT
                  ? null
                  : form.skill_required_id
              }
              dueDate={form.due_date}
              currentAssigneeId={
                form.assigned_to_id === NULL_SELECT ? null : form.assigned_to_id
              }
              onPick={(personId) =>
                setForm((f) => ({ ...f, assigned_to_id: personId }))
              }
            />
          </div>

          <div className="grid gap-1.5">
            <Label htmlFor="wr-notes">Notes</Label>
            <Textarea
              id="wr-notes"
              value={form.notes}
              rows={3}
              onChange={(e) =>
                setForm((f) => ({ ...f, notes: e.target.value }))
              }
            />
          </div>

          {statusBlocker && (
            <div className="text-xs text-amber-700 border border-amber-300 bg-amber-50 rounded px-2 py-1">
              {statusBlocker}
            </div>
          )}

          {submitError && (
            <div className="text-xs text-destructive border border-destructive/40 bg-destructive/10 rounded px-2 py-1">
              {submitError}
            </div>
          )}
        </div>

        <DialogFooter className="gap-2 sm:justify-between">
          {mode === "edit" ? (
            <Button
              variant="ghost"
              className="text-destructive hover:text-destructive"
              onClick={onDelete}
              disabled={isPending}
            >
              Delete
            </Button>
          ) : (
            <span />
          )}
          <div className="flex gap-2">
            <Button
              variant="ghost"
              onClick={() => onOpenChange(false)}
              disabled={isPending}
            >
              Cancel
            </Button>
            <Button onClick={onSubmit} disabled={!canSubmit}>
              {isPending && (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden />
              )}
              {mode === "create" ? "Create" : "Save"}
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default WorkRequestDialog;
